export const POPULAR_LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'pa', name: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'jv', name: 'Javanese', native: 'Basa Jawa' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'vi', name: 'Vietnamese', native: 'Tiếng Việt' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', native: 'मराठी' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்' },
  { code: 'tr', name: 'Turkish', native: 'Türkçe' },
  { code: 'ur', name: 'Urdu', native: 'اردو' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
  { code: 'th', name: 'Thai', native: 'ไทย' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'fa', name: 'Persian', native: 'فارسی' },
  { code: 'pl', name: 'Polish', native: 'Polski' },
  { code: 'uk', name: 'Ukrainian', native: 'Українська' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'or', name: 'Oriya', native: 'ଓଡ଼ିଆ' },
  { code: 'my', name: 'Burmese', native: 'မြန်မာဘာသာ' },
  { code: 'ha', name: 'Hausa', native: 'هَوُسَ' },
  { code: 'am', name: 'Amharic', native: 'አማርኛ' },
  { code: 'ff', name: 'Fula', native: 'Fulfulde' },
  { code: 'yo', name: 'Yoruba', native: 'Yorùbá' },
  { code: 'ig', name: 'Igbo', native: 'Asụsụ Igbo' },
  { code: 'ro', name: 'Romanian', native: 'Română' },
  { code: 'nl', name: 'Dutch', native: 'Nederlands' },
  { code: 'hu', name: 'Hungarian', native: 'Magyar' },
  { code: 'el', name: 'Greek', native: 'Ελληνικά' },
  { code: 'cs', name: 'Czech', native: 'Čeština' },
  { code: 'sv', name: 'Swedish', native: 'Svenska' },
  { code: 'he', name: 'Hebrew', native: 'עברית' },
  { code: 'id', name: 'Indonesian', native: 'Bahasa Indonesia' },
  { code: 'ms', name: 'Malay', native: 'Bahasa Melayu' },
  { code: 'tl', name: 'Tagalog', native: 'Tagalog' },
  { code: 'az', name: 'Azerbaijani', native: 'Azərbaycanca' },
  { code: 'ka', name: 'Georgian', native: 'ქართული' },
  { code: 'hy', name: 'Armenian', native: 'Հայերեն' },
  { code: 'uz', name: 'Uzbek', native: 'Oʻzbekcha' },
  { code: 'kk', name: 'Kazakh', native: 'Қазақ тілі' },
  { code: 'ky', name: 'Kyrgyz', native: 'Кыргызча' },
  { code: 'tg', name: 'Tajik', native: 'Тоҷиκӣ' },
  { code: 'tk', name: 'Turkmen', native: 'Türkmençe' },
  { code: 'ps', name: 'Pashto', native: 'پښتو' },
  { code: 'ku', name: 'Kurdish', native: 'Kurdî' },
  { code: 'km', name: 'Khmer', native: 'ភាសាខ្មែរ' },
  { code: 'lo', name: 'Lao', native: 'ພາສາລາວ' },
  { code: 'si', name: 'Sinhala', native: 'සිංහල' },
  { code: 'ne', name: 'Nepali', native: 'नेपाली' },
  { code: 'dz', name: 'Dzongkha', native: 'རྫོང་ཁ་' },
  { code: 'bo', name: 'Tibetan', native: 'བོད་སྐད་' },
  { code: 'mn', name: 'Mongolian', native: 'Монгол хэл' },
  { code: 'af', name: 'Afrikaans', native: 'Afrikaans' },
  { code: 'xh', name: 'Xhosa', native: 'isiXhosa' },
  { code: 'zu', name: 'Zulu', native: 'isiZulu' },
  { code: 'sw', name: 'Swahili', native: 'Kiswahili' },
  { code: 'no', name: 'Norwegian', native: 'Norsk' },
  { code: 'da', name: 'Danish', native: 'Dansk' },
  { code: 'fi', name: 'Finnish', native: 'Suomi' },
  { code: 'is', name: 'Icelandic', native: 'Íslenska' },
  { code: 'ga', name: 'Irish', native: 'Gaeilge' },
  { code: 'cy', name: 'Welsh', native: 'Cymraeg' },
  { code: 'gd', name: 'Scots Gaelic', native: 'Gàidhlig' },
  { code: 'lb', name: 'Luxembourgish', native: 'Lëtzebuergesch' },
  { code: 'mt', name: 'Maltese', native: 'Malti' },
  { code: 'sq', name: 'Albanian', native: 'Shqip' },
  { code: 'mk', name: 'Macedonian', native: 'Македонски' },
  { code: 'sr', name: 'Serbian', native: 'Српски' },
  { code: 'hr', name: 'Croatian', native: 'Hrvatski' },
  { code: 'bs', name: 'Bosnian', native: 'Bosanski' },
  { code: 'sl', name: 'Slovenian', native: 'Slovenščina' },
  { code: 'sk', name: 'Slovak', native: 'Slovenčina' },
  { code: 'et', name: 'Estonian', native: 'Eesti' },
  { code: 'lv', name: 'Latvian', native: 'Latviešu' },
  { code: 'lt', name: 'Lithuanian', native: 'Lietuvių' },
  { code: 'be', name: 'Belarusian', native: 'Беларуская' },
  { code: 'eu', name: 'Basque', native: 'Euskara' },
  { code: 'gl', name: 'Galician', native: 'Galego' },
  { code: 'ca', name: 'Catalan', native: 'Català' },
  { code: 'oc', name: 'Occitan', native: 'Occitan' },
  { code: 'br', name: 'Breton', native: 'Brezhoneg' },
  { code: 'co', name: 'Corsican', native: 'Corsu' },
  { code: 'fy', name: 'Western Frisian', native: 'Frysk' },
  { code: 'yi', name: 'Yiddish', native: 'ייִדיש' },
  { code: 'la', name: 'Latin', native: 'Latina' },
  { code: 'eo', name: 'Esperanto', native: 'Esperanto' },
];
